### ISSUE TITLE
I can't run the TMCTest on a simulator

### ISSUE THREAD

**Issue by mnovakovic** [tothgy/TMCTest#1]
I cloned the repo and I ran "pod install" and when I open the workspace I don't see any of the Simulators to run this on. (I tried running pod update as well, same thing).

The deployment target is set to 9.3 (aka the default)

I have Xcode 7.2.1.

When I go and manually set the deployment target to 9.2 or 9.0 and restart XCode I can see the simulator but I still can't run the app with the message "The run destination iPhone 6 is not valid for Running the scheme 'TMCTest'."

What am I doing wrong?

**Comment by tothgy** [comment]
Hi @mnovakovic,

I've updated Cocoa Pods to 1.0.1 494b664623a7bfea145f278f44ffb30144d92e99, it's major version change, might have been a configuration issue

check it out and let me know if that fixed it for you

**Comment by mnovakovic** [comment]
I still can't run it :( The deployment is 9.3 still.

**Comment by mnovakovic** [comment]
Ok, so once I switched to XCode 7.3.1 it worked like a charm - might be a useful info to someone!

**Comment by tothgy** [comment]
thanks for having a look, good to hear it has been resolved for you now

I'll check it out at it in Xcode 7.2.1
